In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("E:\dsci510-final-project-boardgame-ratings/data/board_games.csv")
df.head()

,game_id,description,image,max_players,max_playtime,min_age,min_players,min_playtime,name,playing_time,...,artist,category,compilation,designer,expansion,family,mechanic,publisher,average_rating,users_rated
0,1,Die Macher is a game about seven sequential po...,//cf.geekdo-images.com/images/pic159509.jpg,5,240,14,3,240,Die Macher,240,...,Marcus Gschwendtner,"Economic,Negotiation,Political",NaN,Karl-Heinz Schmiel,NaN,"Country: Germany,Valley Games Classic Line","Area Control / Area Influence,Auction/Bidding,...","Hans im Glück Verlags-GmbH,Moskito Spiele,Vall...",7.66508,4498
1,2,Dragonmaster is a trick-taking card game based...,//cf.geekdo-images.com/images/pic184174.jpg,4,30,12,3,30,Dragonmaster,30,...,Bob Pepper,"Card Game,Fantasy",NaN,"G. W. ""Jerry"" D'Arcey",NaN,Animals: Dragons,Trick-taking,"E.S. Lowe,Milton Bradley",6.60815,478
2,3,"Part of the Knizia tile-laying trilogy, Samura...",//cf.geekdo-images.com/images/pic3211873.jpg,4,60,10,2,30,Samurai,60,...,Franz Vohwinkel,"Abstract Strategy,Medieval",NaN,Reiner Knizia,NaN,"Asian Theme,Country: Japan,Knizia tile-laying ...","Area Control / Area Influence,Hand Management,...","999 Games,ABACUSSPIELE,Astrel Games,Ceilikan J...",7.44119,12019
3,4,When you see the triangular box and the luxuri...,//cf.geekdo-images.com/images/pic285299.jpg,4,60,12,2,60,Tal der Könige,60,...,NaN,Ancient,NaN,Christian Beierer,NaN,"Country: Egypt,Promotional Board Games","Action Point Allowance System,Area Control / A...",KOSMOS,6.60675,314
4,5,"In Acquire, each player strategically invests ...",//cf.geekdo-images.com/images/pic342163.jpg,6,90,12,3,90,Acquire,90,...,"Scott Okumura,Peter Whitley",Economic,NaN,Sid Sackson,NaN,3M Bookshelf Series,"Hand Management,Stock Holding,Tile Placement","3M,Avalon Hill,Avalon Hill (Hasbro),Dujardin,G...",7.35830,15195

In [3]:
df_clean = df.copy()

drop_cols = [
    "description", "image", "thumbnail",
    "name", "artist", "publisher",
    "compilation","family", "expansion",
    "category", "mechanic", "designer"
]

df_clean = df_clean.drop(columns=drop_cols)

df_clean.head()

,game_id,max_players,max_playtime,min_age,min_players,min_playtime,playing_time,year_published,average_rating,users_rated
0,1,5,240,14,3,240,240,1986,7.66508,4498
1,2,4,30,12,3,30,30,1981,6.60815,478
2,3,4,60,10,2,30,60,1998,7.44119,12019
3,4,4,60,12,2,60,60,1992,6.60675,314
4,5,6,90,12,3,90,90,1964,7.35830,15195

In [4]:
df_clean.dtypes

game_id             int64
max_players         int64
max_playtime        int64
min_age             int64
min_players         int64
min_playtime        int64
playing_time        int64
year_published      int64
average_rating    float64
users_rated         int64
dtype: object

In [5]:
df_clean.isnull().sum()

game_id           0
max_players       0
max_playtime      0
min_age           0
min_players       0
min_playtime      0
playing_time      0
year_published    0
average_rating    0
users_rated       0
dtype: int64